global:
    scrape_interval: 15s
    evaluation_interval: 15s

alerting:
    alertmanagers:
        - static_configs:
              - targets: []

rule_files:
    # - "first_rules.yml"
    # - "second_rules.yml"

scrape_configs:
    - job_name: "prometheus"
      static_configs:
          - targets: ["localhost:9090"]

    - job_name: "redis_cache"
      scrape_interval: 5s
      metrics_path: /metrics
      static_configs:
          - targets:
                [
                    "cache-service1:3000",
                    "cache-service2:3001",
                    "cache-service3:3002",
                ]
            labels:
                group: "cache-services"
